---
- name: Installing neovim
  community.general.pacman:
    name: neovim
    state: present

- name: Installing language server from pacman
  community.general.pacman:
    name: "{{ lsp_pacman }}"
    state: present

- name: Installing language server from aur
  kewlfft.aur.aur:
    use: makepkg
    name: "{{ lsp_aur }}"
