---
- name: Symlink nvim config
  file:
    src: "{{ role_path }}/files/nvim"
    dest: ~/.config/nvim
    state: link


- name: Symlink vimrc
  file:
    src: "{{ role_path }}/files/vimrc"
    dest: "~/.vimrc"
    state: link

- name: Global gitignore
  file:
    src: "~/git/config/.gitignore"
    dest: "~/.gitignore_global"
    state: link
