---
- name: installing utilities dependencies
  community.general.pacman:
    name: "{{deps}}"
    state: present
  become: true

- name: installing aur utilities
  kewlfft.aur.aur:
    use: makepkg
    name: "{{aur_deps}}"
