---
- name: Installing utilities dependencies
  community.general.pacman:
    name: "{{ deps }}"
    state: present
  become: true

- name: Installing aur utilities
  kewlfft.aur.aur:
    use: makepkg
    name: "{{ aur_deps }}"

- name: Installing fonts
  community.general.pacman:
    name: "{{ fonts }}"
    state: present
  become: true
