---
- name: installing sway
  pacman:
    name: sway
    state: present
  become: true

- name: installing swaylock
  pacman:
    name: swaylock
    state: present
  become: true

- name: installing grim
  pacman:
    name: grim
    state: present
  become: true

- name: installing slurp
  pacman:
    name: slurp
    state: present
  become: true

- name: installing wl-clipboard
  pacman:
    name: wl-clipboard
    state: present
  become: true

- name: installing brightnessctl
  pacman:
    name: brightnessctl
    state: present
  become: true

- name: install i3status
  pacman:
    name: i3status
    state: present
  become: true

- name: install py3status
  pacman:
    name: py3status
    state: present
  become: true

- name: Ensure ~/.config/sway exists
  file:
    path: "~/.config/sway"
    state: directory

- name: Ensure ~/.config/i3status exists
  file:
    path: "~/.config/i3status"
    state: directory

- name: Copy sway config
  file:
    src: "{{ role_path }}/files/config"
    dest: "~/.config/sway/config"
    state: link

- name: Symlink host specific config "~/.config/sway/{{ ansible_hostname }}"
  file:
    src: "{{ role_path }}/files/{{ ansible_hostname }}"
    path: "~/.config/sway/{{ ansible_hostname }}"
    state: link

- name: Copy i3status config
  file:
    src: "{{ role_path }}/files/i3status-config"
    dest: "~/.config/i3status/config"
    state: link

- name: copy Xdefaults
  file:
    src: "{{ role_path }}/files/Xdefaults"
    dest: "~/.Xdefaults"
    state: link

- name: Ensure ~/.config/xdg-desktop-portal-wlr exists
  ansible.builtin.file:
    path: "~/.config/xdg-desktop-portal-wlr"
    state: directory

- name: Ensure ~/.config/xdg-desktop-portal-wlr/config exists
  ansible.builtin.file:
    path: "~/.config/xdg-desktop-portal-wlr/config"
    state: directory

- name: Symlink xdpw config
  ansible.builtin.file:
    src: "{{ role_path }}/files/xdg-desktop-portal-wlr"
    dest: "~/.config/xdg-desktop-portal-wlr/config/config.ini"
    state: link
