---
- name: Installing sway and utilities
  community.general.pacman:
    name: "{{ sway_deps }}"
    state: present
  become: yes

- name: Ensure ~/.config/sway exists
  ansible.builtin.file:
    path: "~/.config/sway"
    state: directory

- name: Ensure ~/.config/i3status exists
  ansible.builtin.file:
    path: "~/.config/i3status"
    state: directory

- name: Copy sway config
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: "~/.config/sway/config"
    state: link

- name: Symlink host specific config "~/.config/sway/{{ ansible_hostname }}"
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ ansible_hostname }}"
    path: "~/.config/sway/{{ ansible_hostname }}"
    state: link

- name: Symlink moniteur scripts
  ansible.builtin.file:
    src: "{{ role_path }}/files/moniteur"
    path: "~/.config/sway/moniteur"
    state: link

- name: Copy i3status config
  ansible.builtin.file:
    src: "{{ role_path }}/files/i3status-config"
    dest: "~/.config/i3status/config"
    state: link

- name: copy Xdefaults
  ansible.builtin.file:
    src: "{{ role_path }}/files/Xdefaults"
    dest: "~/.Xdefaults"
    state: link

- name: Ensure ~/.config/xdg-desktop-portal-wlr exists
  ansible.builtin.file:
    path: "~/.config/xdg-desktop-portal-wlr"
    state: directory

- name: Ensure ~/.config/xdg-desktop-portal-wlr/config exists
  ansible.builtin.file:
    path: "~/.config/xdg-desktop-portal-wlr/config"
    state: directory

- name: Symlink xdpw config
  ansible.builtin.file:
    src: "{{ role_path }}/files/xdg-desktop-portal-wlr"
    dest: "~/.config/xdg-desktop-portal-wlr/config/config.ini"
    state: link
