call plug#begin('~/.vim/pluged')

"async exec
Plug 'Shougo/vimproc.vim', {'do': 'make'}

"Ansible/Yaml
Plug 'chase/vim-ansible-yaml'

"ALE
Plug 'w0rp/ale'

"Darcula theme
Plug 'blueshirts/darcula'

"Dispatch
Plug 'tpope/vim-dispatch'

"easy align
Plug 'junegunn/vim-easy-align'

"Fugitive
Plug 'tpope/vim-fugitive'

"Fuzzy finder
Plug 'junegunn/fzf.vim'

"Gitgutter
Plug 'airblade/vim-gitgutter'

"Green
Plug 'janko/vim-test'

"Jedi
Plug 'davidhalter/jedi-vim'

"Jinja
Plug 'lepture/vim-jinja'

"Pair
Plug 'jiangmiao/auto-pairs'

"Sudo Edit
Plug 'chrisbra/SudoEdit.vim'

"rope
Plug 'python-rope/ropevim'

"rust
Plug 'rust-lang/rust.vim'

"Toml
Plug 'cespare/vim-toml'

"tcomment
Plug 'tomtom/tcomment_vim'

"snippet
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

"YCM
Plug 'Valloric/YouCompleteMe', {'do': './install.py'}

"Better status line
Plug 'vim-airline/vim-airline'
call plug#end()

syntax on
filetype plugin indent on

"general settings
set number
set nocompatible
set hidden
set showcmd
set wildmenu
set backspace=eol,start,indent
set laststatus=2

"get rid of backup file
set nobackup
set nowb
set noswapfile

"indentation management
set expandtab
set smarttab
set autoindent
set smartindent
set shiftwidth=4
set tabstop=4

"search options
set ignorecase
set smartcase
set hlsearch
set showmatch

"make utf8 and unix the default
set encoding=utf8
set ffs=unix,dos,mac

"mapping
let mapleader = ","
noremap <leader>ev :e $HOME/.vimrc<cr>
noremap <leader>rv :source $MYVIMRC<cr>
nnoremap <leader><leader>s :%s/\s+$//ge \| noh <cr>

"autocommand
augroup vimrc
    au!
    "get rid of trailfing white space on write
    au BufWritePre * :%s/\s*$//e | noh | exec 'normal ``zz'
    au BufRead *.yml :setf ansible
augroup end

"theme
set background=dark
colorscheme darcula

"airline
let g:airline_powerline_fonts = 1

"ALE
nnoremap <c-j> :ALENext<cr>
nnoremap <c-k> :ALEPrevious<cr>
let g:ale_linters = {'rust': ['rls']}

"easy align
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)

"Fzf
nnoremap <C-e> :History<cr>
nnoremap <C-p> :Files<cr>

"Ultisnip
let g:UltiSnipExpandTrigger="<tab>"

"Python
au FileType python setlocal shiftwidth=4 softtabstop=4 expandtab

"TComment
noremap <c-m> :TComment<cr>

"Rope
nnoremap <c-enter> :RopeAutoImport<cr>
let g:ropevim_prefer_py3='1'
let g:ropevim_autoimport_modules = ["os", "shutil", "math", "random", "datetime"]

"Ale
let g:ale_python_flake8_options = '--config .flake8'

" jedi-vim {
let g:jedi#auto_vim_configuration = 0
let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0
let g:jedi#completions_enabled = 0
let g:jedi#completions_command = ""
let g:jedi#show_call_signatures = "1"

let g:jedi#goto_assignments_command = "<leader>pa"
let g:jedi#goto_definitions_command = "<leader>pd"
let g:jedi#documentation_command = "<leader>pk"
let g:jedi#usages_command = "<leader>pu"
let g:jedi#rename_command = "<leader>pr"
" }
