syntax on
filetype plugin indent on

"General settings
set sessionoptions-=options
set number
set hidden
set showcmd
set wildmenu
set backspace=eol,start,indent
set laststatus=2
set completeopt+=menuone,longest

"Get rid of backup file
set nobackup
set nowb
set noswapfile

"Indentation management
set expandtab
set smarttab
set autoindent
set smartindent
set shiftwidth=4
set tabstop=4

"Search options
set ignorecase
set smartcase
set hlsearch
set showmatch

"Make utf8 and unix the default
set encoding=utf8
set ffs=unix,dos,mac

"Mapping
let mapleader = ","
noremap <leader>ev :e $HOME/.vimrc<cr>
noremap <leader>rv :source $MYVIMRC<cr>
nnoremap <leader><leader>s :%s/\s+$//ge \| noh <cr>

"theme
set background=dark
colorscheme desert
