---
- name: "Base config"
  hosts: localhost
  pre_tasks:
    - name: Create standard config dir
      file:
        path: "~/.config"
        state: directory

  roles:
    - editor
    - ssh
    - utilities
    - sway
